default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: false
  host: localhost
  username: slashflex
  password: Tutt1_grupp1

development:
  <<: *default
  database: pokedex

